var json_SectorOfficeManualRainfallStations_8 = {
"type": "FeatureCollection",
"name": "SectorOfficeManualRainfallStations_8",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Station Number": "V69344", "Station Name": "FSC Nagigi Bucaisau Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Macuata", "Authority": "FSC", "Station Start": "1.01.1956", "Latitude": -16.35, "Longitude": 179.4333, "Elevation(m)": 51.0 }, "geometry": { "type": "Point", "coordinates": [ 179.4333, -16.35 ] } },
{ "type": "Feature", "properties": { "Station Number": "V69351", "Station Name": "FSC\nWainikoro Sector Office", "Station Type": "Sector Office Manual\nRainfall Station", "Province": "Macuata", "Authority": "FSC", "Station Start": "1.01.1956", "Latitude": -16.3, "Longitude": 179.45, "Elevation(m)": 11.0 }, "geometry": { "type": "Point", "coordinates": [ 179.45, -16.3 ] } },
{ "type": "Feature", "properties": { "Station Number": "V69433", "Station Name": "FSC\nWailevu Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Macuata", "Authority": "FSC", "Station Start": "1.01.1950", "Latitude": -16.4333, "Longitude": 179.3333, "Elevation(m)": 21.9 }, "geometry": { "type": "Point", "coordinates": [ 179.3333, -16.4333 ] } },
{ "type": "Feature", "properties": { "Station Number": "V69434", "Station Name": "FSC\nWaiqele Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Macuata", "Authority": "FSC", "Station Start": "1.01.1954", "Latitude": -16.4667, "Longitude": 179.3333, "Elevation(m)": 19.0 }, "geometry": { "type": "Point", "coordinates": [ 179.3333, -16.4667 ] } },
{ "type": "Feature", "properties": { "Station Number": "V69541", "Station Name": "FSC\nVunimoli Vunicuicui Sector Office", "Station Type": "Sector Office Manual\nRainfall Station", "Province": "Macuata", "Authority": "FSC", "Station Start": "1.01.1951", "Latitude": -16.5167, "Longitude": 179.4, "Elevation(m)": 13.0 }, "geometry": { "type": "Point", "coordinates": [ 179.4, -16.5167 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77481", "Station Name": "FSC\nYaladro Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1938", "Latitude": -17.4167, "Longitude": 177.8833, "Elevation(m)": 9.0 }, "geometry": { "type": "Point", "coordinates": [ 177.8833, -17.4167 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77482", "Station Name": "FSC\nTagitagi Sector Office", "Station Type": "Sector Office Manual\nRainfall Station", "Province": "Ba", "Authority": "FSC", "Station Start": "1.05.1947", "Latitude": -17.4167, "Longitude": 177.8, "Elevation(m)": 9.0 }, "geometry": { "type": "Point", "coordinates": [ 177.8, -17.4167 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77551", "Station Name": "FSC Drasa Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1925", "Latitude": -17.5833, "Longitude": 177.5333, "Elevation(m)": 35.0 }, "geometry": { "type": "Point", "coordinates": [ 177.5333, -17.5833 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77562", "Station Name": "FSC Mota Sector Office", "Station Type": "Sector Office Manual\nRainfall Station", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1938", "Latitude": -17.5833, "Longitude": 177.6833, "Elevation(m)": 30.0 }, "geometry": { "type": "Point", "coordinates": [ 177.6833, -17.5833 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77563", "Station Name": "FSC Sarava Varoka Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1938", "Latitude": -17.5167, "Longitude": 177.65, "Elevation(m)": 18.0 }, "geometry": { "type": "Point", "coordinates": [ 177.65, -17.5167 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77571", "Station Name": "FSC\nVeisaru Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1934", "Latitude": -17.55, "Longitude": 177.7333, "Elevation(m)": 39.0 }, "geometry": { "type": "Point", "coordinates": [ 177.7333, -17.55 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77572", "Station Name": "FSC\nKoronubu Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1938", "Latitude": -17.5833, "Longitude": 177.7333, "Elevation(m)": 25.0 }, "geometry": { "type": "Point", "coordinates": [ 177.7333, -17.5833 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77574", "Station Name": "FSC\nVaravu Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1945", "Latitude": -17.5167, "Longitude": 177.7, "Elevation(m)": 20.0 }, "geometry": { "type": "Point", "coordinates": [ 177.7, -17.5167 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77646", "Station Name": "FSC\nSaweni Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FMS", "Station Start": "1.01.1956", "Latitude": -17.6667, "Longitude": 177.4167, "Elevation(m)": 16.0 }, "geometry": { "type": "Point", "coordinates": [ 177.4167, -17.6667 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77741", "Station Name": "FSC\nMeigunyah Sector Office", "Station Type": "Sector Office Manual Rainfall\nStation", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1930", "Latitude": -17.7833, "Longitude": 177.4667, "Elevation(m)": 18.0 }, "geometry": { "type": "Point", "coordinates": [ 177.4667, -17.7833 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77742", "Station Name": "FSC\nNatova Sector Office", "Station Type": "Sector Office Manual\nRainfall Station", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1936", "Latitude": -17.7333, "Longitude": 177.4667, "Elevation(m)": 9.0 }, "geometry": { "type": "Point", "coordinates": [ 177.4667, -17.7333 ] } },
{ "type": "Feature", "properties": { "Station Number": "V77843", "Station Name": "FSC\nMalolo Sector Office", "Station Type": "Sector Office Manual\nRainfall Station", "Province": "Ba", "Authority": "FSC", "Station Start": "1.01.1959", "Latitude": -17.8167, "Longitude": 177.4, "Elevation(m)": 14.0 }, "geometry": { "type": "Point", "coordinates": [ 177.4, -17.8167 ] } }
]
}
